baseURL = "https://manasranjanpati.netlify.com/"
languageCode = "en-gb"
title = "Manas Ranjan Pati"
theme = "manas"

pygmentsCodeFences = "true"
pygmentsStyle = "perldoc"

# If you want to track using GA or use disqus for comments, uncomment the 
# following and add the correct values
#googleanalytics = ""
#disqusShortname = ""

# The settings below are used throughout the theme.
# Please update!
[params]
  title = "Manas Ranjan Pati"
  tagline = "Developer, Writer, Enthusiast"
  author = "Manas Ranjan Pati"

# If you do not want a social icon, just comment it out
# Please update the example values!
[social]
  email = "mailto:manasranjanpati94@gmail.com"
  facebook = "https://www.facebook.com/#"
  twitter = "https://twitter.com/Iam_manas"
  medium = "https://www.medium.com/@Iam_manas"
  github = "https://github.com/Manasranjanpati"
  linkedin = "https://www.linkedin.com/in/manas-ranjan-pati-0969009a/"
  instagram = "https://www.instagram.com/manasranjanpati/"


# Set unsafe mode to allow markdownify to work with goldmark
# This is important. Please do not delete. It is used to re-render markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
